"""The pentagonal (golden-ratio) world: de Grey's G126 and the (a)-half of a
6-chromatic program, exactly in Q(zeta_5).

Facts from the literature (Parts, arXiv:2010.12656; de Grey; Huddleston;
Exoo--Ismailescu): the plane with BOTH distances {1, phi} forbidden needs at
least 6 colours, phi = (sqrt5+1)/2, witnessed explicitly by

    G126 = G5 (+) G5 (+) G5 (+) G5 (+) G5      (Minkowski sum, 126 vertices)

where G5 is a regular pentagon of side 1 (diagonal phi).  In forcing terms:
every proper unit-edge 5-colouring of G126's points has a monochromatic
phi-pair -- the aggregate forcer, one level up from de Grey's L.

Exact representation: V_k = zeta_5^k / (zeta_5 - 1) has consecutive
differences zeta_5^k (unit sides) and second differences zeta_5^k(zeta_5+1)
with |zeta_5+1| = 2cos(pi/5) = phi (diagonals).  Everything lives in
Q(zeta_5), degree 4, and phi^2 = phi + 1 = (3+sqrt5)/2 is in its real
subfield.  Minkowski sums stay in the ring generated by the vertices.

This module builds G126, verifies the aggregate property from scratch, and
exposes the phi-pair machinery for the (b)-half hunt.
"""

import time
from itertools import combinations_with_replacement

from cyclo import get_cyclofield
from udg import UDG
from colour import ColourInstance, k_colourable, verify_colouring


def field():
    return get_cyclofield(5)


def pentagon(fld):
    """Unit-side pentagon: V_k = zeta^k / (zeta - 1)."""
    inv = fld.inv(fld.sub(fld.zeta(1), fld.one))
    return [fld.mul(fld.zeta(k), inv) for k in range(5)]


def phi2(fld):
    """phi^2 = phi + 1 as a field element: |zeta+1|^2 = (zeta+1)(zeta^-1+1)."""
    w = fld.add(fld.zeta(1), fld.one)
    return fld.norm2(w)


def minkowski_power(fld, base, n):
    """All sums of n points of `base` (with repetition) -- G5^(+)n."""
    pts = set()
    for combo in combinations_with_replacement(range(len(base)), n):
        z = fld.zero
        for i in combo:
            z = fld.add(z, base[i])
        pts.add(z)
    return sorted(pts)


def phi_pairs(fld, g):
    """All vertex pairs at exact distance phi."""
    target = phi2(fld)
    import math
    phi_f = (5 ** 0.5 + 1) / 2
    fl = [fld.pfloat(p) for p in g.points]
    out = []
    for i in range(len(g)):
        xi, yi = fl[i]
        for j in range(i + 1, len(g)):
            dx, dy = xi - fl[j][0], yi - fl[j][1]
            if abs(dx * dx + dy * dy - phi_f * phi_f) > 1e-6:
                continue
            if fld.dist2(g.points[i], g.points[j]) == target:
                out.append((i, j))
    return out


def build_G126(fld=None):
    fld = fld or field()
    pts = minkowski_power(fld, pentagon(fld), 5)
    return UDG(fld, pts)


def aggregate_phi_test(g, k=5, log=print):
    """Can g be k-coloured (unit edges proper) with no mono phi-pair?

    UNSAT = the aggregate forcer property.  For G126 the literature says
    UNSAT (two-distance chromatic number 6); we verify from scratch.
    """
    fld = g.fld
    pairs = phi_pairs(fld, g)
    log(f"  phi-pairs: {len(pairs)}")
    inst = ColourInstance(g, k)
    for u, v in pairs:
        for c in range(k):
            inst.add_clause([-inst.var(u, c), -inst.var(v, c)])
    t0 = time.time()
    sat, col = inst.solve()
    dt = time.time() - t0
    if sat:
        ok, _ = verify_colouring(g, col)
        assert ok and all(col[u] != col[v] for u, v in pairs)
        log(f"  SAT in {dt:.1f}s -- NOT an aggregate forcer at k={k}")
    else:
        log(f"  UNSAT in {dt:.1f}s -- aggregate forcer CONFIRMED at k={k}")
    return not sat


if __name__ == "__main__":
    fld = field()
    P = pentagon(fld)
    # sanity: unit sides, phi diagonals, exactly
    side_ok = all(fld.is_unit(P[i], P[(i + 1) % 5]) for i in range(5))
    diag_ok = all(fld.dist2(P[i], P[(i + 2) % 5]) == phi2(fld) for i in range(5))
    print(f"pentagon: unit sides {side_ok}, phi diagonals {diag_ok}")

    for n in (2, 3, 4, 5):
        g = UDG(fld, minkowski_power(fld, P, n))
        print(f"G5^(+){n}: {g.summary()}")
        if n == 5:
            print(f"  (paper: 126 vertices, 350 unit edges)")
            print("aggregate phi test at k=5:")
            forcer = aggregate_phi_test(g, 5)
            print("aggregate phi test at k=4 (should also be UNSAT a fortiori):")
            aggregate_phi_test(g, 4)
            # and where does forcing STOP? k=6 must be SAT or chi(d)>=7 news
            print("aggregate phi test at k=6 (expect SAT):")
            aggregate_phi_test(g, 6)
